name: 'GitHub CI: Dev Build'

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches:
      - 'develop'

jobs:
  dev_build:
    runs-on: windows-latest
    steps:
    - name: Format push time
      if: success()
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ github.event.repository.pushed_at }}"
        replace-with: '-'
        flags: 'g'

    - name: Set VSIX name environment variable
      run: echo '::set-env name=VSIX_NAME::papyrus-lang-test-${{ steps.format-time.outputs.replaced }}.vsix'
          
    - name: Notify Build Started
      uses: rjstone/discord-webhook-notify@v1
      if: github.ref == 'refs/heads/develop'
      with:
        severity: warn
        description: |
          New build [${{ github.workflow }}](https://github.com/joelday/papyrus-lang/actions) \(${{ github.ref }}\)
          started by ${{ github.actor }}. (**${{ github.repository }}** got **${{ github.event_name }}** for **${{ github.ref }}**)
          Building ${{ env.VSIX_NAME }}....
        footer: Build Started
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Nuget.exe
      if: success()
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Update Debug
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: update-debug-plugin

    - name: Update Pyro
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: update-pyro-cli

    - name: Full Build (default)
      if: success()
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: default

    - name: VSCE Package
      if: ${{ success() }}
      run: > 
        cd src\papyrus-lang-vscode ;
        npm install vsce ;
        mkdir artifact ;
        npx vsce package -o artifact\${{ env.VSIX_NAME }}
 
    - name: Upload artifact
      if: ${{ success() && github.ref == 'refs/heads/develop' }}
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.VSIX_NAME }}
        path: src\papyrus-lang-vscode\artifact\${{ env.VSIX_NAME }}
 
    # Notifications
    - name: Notify Success
      if: ${{ success() && github.ref == 'refs/heads/develop' }}
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        description: '**Build Succeeded!** ${{ github.ref }} https://github.com/joelday/papyrus-lang/actions'
        footer: Build Ended (Success)
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Notify Failure
      if: ${{ failure() && github.ref == 'refs/heads/develop' }}
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: error
        description: '**Build Failed!** ${{ github.ref }} ${{ env.VSIX_NAME }}'
        footer: Build Ended (Error)
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Notify Cancelled
      if: ${{ cancelled() && github.ref == 'refs/heads/develop' }}
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: warn
        description: '**Build Cancelled!** ${{ github.ref }} ${{ env.VSIX_NAME }}'
        footer: Build Ended (Warning)
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
